apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-config
  name: pod-config
spec:
  volumes:
    - name: app-config-vol
      configMap:
        name: app-config
  containers:
  - image: busybox
    name: pod-config
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
      - name: app-config-vol
        mountPath: /etc/config
