apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - image: busybox
    name: pod1
    command: ["sh","-c","env && sleep 3600"]
    envFrom:
    - configMapRef:
        name: env-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
