apiVersion: v1
kind: Pod
metadata:
  name: config-reader
spec:
  volumes:
    - name: config-volume
      configMap:
        name: app-properties
  containers:
    - name: app-properties
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "ls /etc/config && sleep 3600"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
