apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingres
spec:
  podSelector:
    matchLabels:
      app: secure
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: trusted
    ports:
    - protocol: TCP
      port: 8080
