apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  defaultBackend:
    service:
      name: default-svc
      port:
        number: 80
  rules:
  - host: myapp.com
    http:
      paths:
      - backend:
          service:
            name: app-svc
            port:
              number: 8080
        path: /app
        pathType: Prefix
status:
  loadBalancer: {}
