apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-ingress
spec:
  rules:
  - host: store.com
    http:
      paths:
      - backend:
          service:
            name: product-svc
            port:
              number: 8080
        path: /products
        pathType: Prefix
      - backend:
          service:
            name: order-svc
            port:
              number: 8080
        path: /orders
        pathType: Prefix
      - backend:
          service:
            name: user-svc
            port:
              number: 8080
        path: /users
        pathType: Prefix
status:
  loadBalancer: {}
